// This file was auto-generated by ML.NET Model Builder. 

using System;
using DemoAppML.Model;

namespace DemoAppML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Artikel_Nr = @"Art001",
                Lagerort = 1F,
                Menge_In = 100F,
                Menge_Out = 10F,
                Artikeltyp = @"Eigenfertigung",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Gesamt_Artikelbestand with predicted Gesamt_Artikelbestand from sample data...\n\n");
            Console.WriteLine($"Artikel_Nr: {sampleData.Artikel_Nr}");
            Console.WriteLine($"Lagerort: {sampleData.Lagerort}");
            Console.WriteLine($"Menge_In: {sampleData.Menge_In}");
            Console.WriteLine($"Menge_Out: {sampleData.Menge_Out}");
            Console.WriteLine($"Artikeltyp: {sampleData.Artikeltyp}");
            Console.WriteLine($"\n\nPredicted Gesamt_Artikelbestand value {predictionResult.Prediction} \nPredicted Gesamt_Artikelbestand scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
